export const ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 40001,
  TOKEN_EXPIRED: 40002,
  CAPTCHA_REQUIRED: 40003,
  CAPTCHA_INVALID: 40004,

  // Permission errors
  FORBIDDEN: 40301,
  INSUFFICIENT_PERMISSIONS: 40302,

  // Validation errors
  VALIDATION_ERROR: 42201,
  SCHEDULE_CONFLICT: 42202,
  LICENSE_CONFLICT: 42203,

  // Business errors
  TASK_NOT_FOUND: 40401,
  EMPLOYEE_NOT_FOUND: 40402,
  CUSTOMER_NOT_FOUND: 40403,

  // Server errors
  INTERNAL_ERROR: 50001,
} as const;

export const ERROR_MESSAGES: Record<number, string> = {
  [ERROR_CODES.INVALID_CREDENTIALS]: '帳號或密碼錯誤',
  [ERROR_CODES.TOKEN_EXPIRED]: '登入已過期，請重新登入',
  [ERROR_CODES.CAPTCHA_REQUIRED]: '請輸入驗證碼',
  [ERROR_CODES.CAPTCHA_INVALID]: '驗證碼錯誤',
  [ERROR_CODES.FORBIDDEN]: '無此操作權限',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '權限不足',
  [ERROR_CODES.VALIDATION_ERROR]: '資料驗證失敗',
  [ERROR_CODES.SCHEDULE_CONFLICT]: '排班衝突',
  [ERROR_CODES.LICENSE_CONFLICT]: '證照衝突',
  [ERROR_CODES.TASK_NOT_FOUND]: '找不到該任務',
  [ERROR_CODES.EMPLOYEE_NOT_FOUND]: '找不到該員工',
  [ERROR_CODES.CUSTOMER_NOT_FOUND]: '找不到該客戶',
  [ERROR_CODES.INTERNAL_ERROR]: '伺服器錯誤，請稍後再試',
};
