// Permission codes for route and UI element access control
export const PERMISSIONS = {
  // Task Management
  TASK_VIEW: 'task:view',
  TASK_CREATE: 'task:create',
  TASK_EDIT: 'task:edit',
  TASK_DELETE: 'task:delete',
  TASK_EXPORT: 'task:export',
  TASK_OVERRIDE_ALERT: 'task:override_alert',

  // Schedule
  SCHEDULE_VIEW: 'schedule:view',
  SCHEDULE_EDIT: 'schedule:edit',
  SCHEDULE_APPROVE: 'schedule:approve',

  // Customer
  CUSTOMER_VIEW: 'customer:view',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_EDIT: 'customer:edit',
  CUSTOMER_DELETE: 'customer:delete',

  // Employee
  EMPLOYEE_VIEW: 'employee:view',
  EMPLOYEE_CREATE: 'employee:create',
  EMPLOYEE_EDIT: 'employee:edit',
  EMPLOYEE_DESIGNATE_LEAVE: 'employee:designate_leave',

  // Notification
  NOTIFICATION_VIEW: 'notification:view',
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_MANAGE_TEMPLATE: 'notification:manage_template',

  // Approval
  APPROVAL_VIEW: 'approval:view',
  APPROVAL_APPROVE: 'approval:approve',

  // Pending Customer
  PENDING_CUSTOMER_VIEW: 'pending_customer:view',
  PENDING_CUSTOMER_CREATE: 'pending_customer:create',
  PENDING_CUSTOMER_CONVERT: 'pending_customer:convert',

  // Map
  MAP_VIEW: 'map:view',

  // System
  SYSTEM_AUDIT: 'system:audit',
  SYSTEM_SETTINGS: 'system:settings',
} as const;

// Role-based permission mapping
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  ADMIN_STAFF: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_EXPORT,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_EDIT,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_MANAGE_TEMPLATE,
    PERMISSIONS.PENDING_CUSTOMER_VIEW,
    PERMISSIONS.PENDING_CUSTOMER_CREATE,
    PERMISSIONS.PENDING_CUSTOMER_CONVERT,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.MAP_VIEW,
  ],
  MANAGER: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_OVERRIDE_ALERT,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_APPROVE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.MAP_VIEW,
  ],
  DIRECTOR: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_OVERRIDE_ALERT,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_APPROVE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.EMPLOYEE_DESIGNATE_LEAVE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.MAP_VIEW,
  ],
  LEADER: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_OVERRIDE_ALERT,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_DESIGNATE_LEAVE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.MAP_VIEW,
  ],
  STAFF: [PERMISSIONS.TASK_VIEW, PERMISSIONS.SCHEDULE_VIEW, PERMISSIONS.NOTIFICATION_VIEW],
  SALES_OPS: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.MAP_VIEW,
  ],
};
